### ISSUE TITLE
ERROR: "dev:parcel" exited with 1. when run `npm run start`

### ISSUE THREAD

**Issue by khoivan88** [stevepolitodesign/eleventy-bootstrap-starter#5]
Hi,

First, thank you for your blog post and this repo. I am recently getting into using 11ty and wanted to do some bundling with parcel. I was following your post to get to understand it more. However, upon running `npm run start`, I got this following error in the terminal. 
This is the exact clone of this repo:

```bash
npmcodespace ➜ ~/workspace/eleventy-bootstrap-starter (master) $ npm run start

> eleventy-bootstrap-starter@1.0.0 start /home/codespace/workspace/eleventy-bootstrap-starter
> npm-run-all --parallel dev:*

sh: 1: npm-run-all: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! eleventy-bootstrap-starter@1.0.0 start: `npm-run-all --parallel dev:*`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the eleventy-bootstrap-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codespace/.npm/_logs/2020-11-01T20_24_19_182Z-debug.log
codespace ➜ ~/workspace/eleventy-bootstrap-starter (master) $ 
```

And this is the content of the log file:
```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/opt/nodejs/12.16.3/bin/node',
1 verbose cli   '/opt/nodejs/lts/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle eleventy-bootstrap-starter@1.0.0~prestart: eleventy-bootstrap-starter@1.0.0
6 info lifecycle eleventy-bootstrap-starter@1.0.0~start: eleventy-bootstrap-starter@1.0.0
7 verbose lifecycle eleventy-bootstrap-starter@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle eleventy-bootstrap-starter@1.0.0~start: PATH: /opt/nodejs/12.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/codespace/workspace/eleventy-bootstrap-starter/node_modules/.bin:/usr/local/go/bin:/go/bin:/usr/local/cargo/bin:/home/codespace/.dotnet:/home/codespace/.nvm/current/bin:/home/codespace/.dotnet/tools:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/cargo/bin:/usr/local/go/bin:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/oryx:/opt/nodejs/lts/bin:/opt/dotnet/sdks/lts:/opt/python/latest/bin:/opt/php/lts/bin:/opt/php-composer:/opt/yarn/stable/bin:/opt/hugo/lts:/usr/local/py-utils/bin:/home/codespace/.vscode-remote/bin/16f4a29aa0ac05d3cba222b1f347b7404626c680/bin:/usr/local/rvm/gems/ruby-2.7.0/bin:/usr/local/rvm/gems/ruby-2.7.0@global/bin:/usr/local/rvm/rubies/ruby-2.7.0/bin:/usr/local/go/bin:/go/bin:/usr/local/cargo/bin:/home/codespace/.dotnet:/home/codespace/.nvm/current/bin:/home/codespace/.dotnet/tools:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/cargo/bin:/usr/local/go/bin:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/oryx:/opt/nodejs/lts/bin:/opt/dotnet/sdks/lts:/opt/python/latest/bin:/opt/php/lts/bin:/opt/php-composer:/opt/yarn/stable/bin:/opt/hugo/lts:/usr/local/py-utils/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/codespace/.local/bin:/home/codespace/.npm-global/bin:/usr/local/py-utils/bin:/usr/local/rvm/bin:/home/codespace/.local/bin:/home/codespace/.npm-global/bin:/usr/local/py-utils/bin
9 verbose lifecycle eleventy-bootstrap-starter@1.0.0~start: CWD: /home/codespace/workspace/eleventy-bootstrap-starter
10 silly lifecycle eleventy-bootstrap-starter@1.0.0~start: Args: [ '-c', 'npm-run-all --parallel dev:*' ]
11 info lifecycle eleventy-bootstrap-starter@1.0.0~start: Failed to exec start script
12 verbose stack Error: eleventy-bootstrap-starter@1.0.0 start: `npm-run-all --parallel dev:*`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/12.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:310:20)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid eleventy-bootstrap-starter@1.0.0
14 verbose cwd /home/codespace/workspace/eleventy-bootstrap-starter
15 verbose Linux 5.4.0-1031-azure
16 verbose argv "/opt/nodejs/12.16.3/bin/node" "/opt/nodejs/lts/bin/npm" "run" "start"
17 verbose node v12.16.3
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error eleventy-bootstrap-starter@1.0.0 start: `npm-run-all --parallel dev:*`
23 error spawn ENOENT
24 error Failed at the eleventy-bootstrap-starter@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

I have tried to clear npm cache, remove `node_modules` and `package-lock.json` and rerun `npm install` but it did not help!

I was wondering if you might have a suggestion?

Thank you very much!

**Comment by khoivan88** [comment]
I found the issue, I did not run `npm install` in the github codespace ahead of time!!
